.PHONY:clean
#main:memmove.c
#	gcc -o $@ $^
#main:memcpy.c
#	gcc -o $@ $^
#main:strcmp.c
#	gcc -o $@ $^
main:strstr.c
	gcc -o $@ $^
#main:strcat.c
#	gcc -o $@ $^
#main:strcpy.c
#	gcc -o $@ $^
#main:strlen.c
#	gcc -o $@ $^
clean:
	rm -rf main
